repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -  id: flake8
repos:
-   repo: https://github.com/psf/black
    rev: latest
    hooks:
    -  id: black
    -  args: ["--config", "pyproject.toml"]