language: python
python:
  - "3.8.0"
# command to install depencdencies
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install black
# command to run tests
script:
  - flake8 .
  - black --check .
  - pytest

branches:
  only:
  - master